# the name of your site, e.g. ACME Corp.
title: Jekyll Theme TSieczko

author:
  name: Author Name
  email: name@email.com

contacts:
  GitHub: https://github.com
  LinkedIn: https://www.linkedin.com
